### ISSUE TITLE
Yolov7 API Conversion issue

### ISSUE THREAD

**Issue by CJavier11** [luxonis/tools#36]
Hello, 
I believe the recent customizable shaves option push made it so I can't connect with the Luxonis yolov7 conversion. Here is my source code

```
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
from typing import Union, Tuple
import requests
from uuid import uuid4
import multiprocessing
import time
import json

_URL =  "https://tools.luxonis.com/yolov7" #"http://tools.luxonis.com/upload"
_OUTPUT_FILE_NAME = "output.zip"
_FRACTIONS = {
    "none": 0,
    "read": 0.1,
    "initialized": 0.3,
    "onnx": 0.5,
    "openvino": 0.65,
    "blob": 0.8,
    "json": 0.9,
    "zip": 1
}

def get_progress(key):
    
    print("Progress")
    bar_length = 20
    curr = "|"
    
    while(True):
        # get progress
        r = requests.get(f"{_URL}/progress/{key}")
        r = json.loads(r.text)
        
        # bar
        fraction = _FRACTIONS[r["progress"]]
        arrow = int(fraction * bar_length - 1) * '-' + '>'
        padding = int(bar_length - len(arrow)) * ' '
        ending = '\n' if fraction == 1 else '\r'
        curr = "|" if curr == "-" else "-"
        print(f'Progress: [{arrow}{padding}] {int(fraction*100)}% {curr}', end=ending)
        
        time.sleep(1)


def convert_yolo(file_path: str, shape: Union[int, Tuple[int, int]] = 416, version: Literal["v7"] = "v7"):
    """ Uploads Yolo weights and receives zip with compiled blob.
    
    :param file_path: Path to .pt weights
    :param shape: Integer or tuple with width and height - must be divisible by 32
    :param version: Version of the Yolo model
    :returns: Path to downloaded zip file
    :param file_path: Path to .pt weights
    """
    
    # variables
    files = {'file': open(file_path,'rb')}
    values = {
        'inputshape': shape if isinstance(shape, int) else " ".join(map(str,shape)), 
        'version': version, 
        'id': uuid4()
    }
    file_name = _OUTPUT_FILE_NAME
    url = f"{_URL}/upload"
    print(url)
    
    # progress bar
    proc = multiprocessing.Process(target=get_progress, args=(str(values["id"]),))
    proc.start()
    
    # upload files
    session = requests.Session()
    with session.post(url, files=files, data=values, stream=True) as r:
        
        r.raise_for_status()
        proc.terminate()
        print(f"Conversion complete. Downloading...")
        
        with open(file_name, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192): 
                # If you have chunk encoded response uncomment if
                # and set chunk_size parameter to None.
                #if chunk: 
                f.write(chunk)
    return file_name
```

Here is the output

<img width="898" alt="Screenshot 2023-03-04 at 6 37 30 PM" src="https://user-images.githubusercontent.com/90358358/222933542-086fb1d3-8184-4e16-9bbd-58a115a0203a.png">

Cheers!

**Comment by HonzaCuhel** [comment]
Hello @CJavier11,

thank you for reporting this! We have looked at it and found out that the problem was that since we deployed the last version of tools with the customizable shaves option, the request handler function in the tools required another field in its payload (which is `nShaves` - where the number of shaves is specified), which wasn't set in your script and that was why it was failing. We have fixed that by making the field `nShaves` optional and deployed the change, so now your script should be working again (I have tested it, and it worked for me). 

If you'd be curious to see how you could specify the number of shaves in your script, I took the liberty of updating it, and I'd like to share it here with you:

```
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
from typing import Union, Tuple
import requests
from uuid import uuid4
import multiprocessing
import time
import json

_URL =  "https://tools.luxonis.com/yolov7" #"http://tools.luxonis.com/upload"
_OUTPUT_FILE_NAME = "output.zip"
_FRACTIONS = {
    "none": 0,
    "read": 0.1,
    "initialized": 0.3,
    "onnx": 0.5,
    "openvino": 0.65,
    "blob": 0.8,
    "json": 0.9,
    "zip": 1
}

def get_progress(key):
    
    print("Progress")
    bar_length = 20
    curr = "|"
    
    while(True):
        # get progress
        r = requests.get(f"{_URL}/progress/{key}")
        r = json.loads(r.text)
        
        # bar
        fraction = _FRACTIONS[r["progress"]]
        arrow = int(fraction * bar_length - 1) * '-' + '>'
        padding = int(bar_length - len(arrow)) * ' '
        ending = '\n' if fraction == 1 else '\r'
        curr = "|" if curr == "-" else "-"
        print(f'Progress: [{arrow}{padding}] {int(fraction*100)}% {curr}', end=ending)
        
        time.sleep(1)


def convert_yolo(file_path: str, shape: Union[int, Tuple[int, int]] = 416, nShaves: int = 6, version: Literal["v7"] = "v7"):
    """ Uploads Yolo weights and receives zip with compiled blob.
    
    :param file_path: Path to .pt weights
    :param shape: Integer or tuple with width and height - must be divisible by 32
    :param nShaves: Integer specifying the number of shaves the model will be converted with
    :param version: Version of the Yolo model
    :returns: Path to downloaded zip file
    :param file_path: Path to .pt weights
    """
    
    # variables
    files = {'file': open(file_path,'rb')}
    values = {
        'inputshape': shape if isinstance(shape, int) else " ".join(map(str,shape)), 
        'version': version,
        'nShaves': nShaves,
        'id': uuid4()
    }
    file_name = _OUTPUT_FILE_NAME
    url = f"{_URL}/upload"
    print(url)
    
    # progress bar
    proc = multiprocessing.Process(target=get_progress, args=(str(values["id"]),))
    proc.start()
    
    # upload files
    session = requests.Session()
    with session.post(url, files=files, data=values, stream=True) as r:
        
        r.raise_for_status()
        proc.terminate()
        print(f"Conversion complete. Downloading...")
        
        with open(file_name, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192): 
                # If you have chunk encoded response uncomment if
                # and set chunk_size parameter to None.
                #if chunk: 
                f.write(chunk)
    return file_name
 ```
 
 Best
 Jan

**Comment by CJavier11** [comment]
Hi Jan, 

I'm still running into an error with that script
 HTTPError: 523 Server Error: UNKNOWN for url: https://tools.luxonis.com/yolov7/upload

**Comment by HonzaCuhel** [comment]
Hi @CJavier11,

could you please share with me the exact model that you are trying to convert and the exact script that you are using? Also, could you maybe try to convert a different model (different weights) to see if it works, please? Because I have tried your script again multiple times now and everytime it has worked for me.

Best
Jan

**Comment by CJavier11** [comment]
I am able to use the tools.luxonis.com converter webpage just fine to convert my model.  I was using the script sent above alongside this

```
from yolo_conversion_api import convert_yolo

fn = convert_yolo(x_weights, export_size, yolo_v)
```

of which I import the yolo_conversion_api from the script, I then feed it my weights path, export size (640,352) and 'v7'.  Am I missing something based upon the above script and my function call?

**Comment by HonzaCuhel** [comment]
Could you please share with me the model that you are trying to convert (e.g. via Google Drive), so that I can try it? Because I cannot reproduce your error. I am testing it with `yolov7-tiny`. I did exactly what you are describing (created script `yolo_conversion_api.py` and putted there the code that you've shared and a test script, where I import the `convert_yolo()` function and call it like this `fn = convert_yolo('yolov7t.pt', (640,352), 'v7')`) and it worked. 

No, the `nShaves` doesn't have to be specified in the API call, it is an optional argument. 

What exactly is the error that it returns? Are you sure that you haven't somehow changed the `convert_yolo()` function?

**Comment by CJavier11** [comment]
This is the exact error I've been getting returned, the script is exactly what was sent above

<img width="786" alt="Screenshot 2023-03-06 at 3 57 29 PM" src="https://user-images.githubusercontent.com/90358358/223228992-777cd74b-9d3b-46c8-87a3-86eb4e3d1616.png">

I've attached a google drive link to the model

https://drive.google.com/drive/folders/1nDhBUSdKR-kLFsxd5JEDxBTr7m_APqYR?usp=sharing

**Comment by HonzaCuhel** [comment]
I have tried to convert your model and it has worked for me. I'm sharing with you the scripts that I used. Here's the [link](https://drive.google.com/file/d/1ZWuPAKa1PLvREsFzEWzk_6MxF7g4au4P/view?usp=sharing). Please try to run it (using `python3 test.py`) and see if it works. If it works, please compare it with your code and try to find the differences. 

In the tools, we use error 523 for when there was a problem while converting to blob, but since I can't replicate, I can't see what is wrong.

**Comment by CJavier11** [comment]
Hello,

I am using this script on google collab and the issue still persists with the error 523, I've now tried this with 3/4 different yolov7 models and the convert script.
