### ISSUE TITLE
Trying to convert trained(.pt file) Yolo model on tools.luxonis.com

### ISSUE THREAD

**Issue by Fakhrillo** [luxonis/tools#73]
Hey guys, I'm trying to convert my trained yolov6n model (.pt file) on tools.luxonis.com to a blob file to use on the OAK camera, but I'm getting an error like this:

![image](https://github.com/luxonis/tools/assets/62103175/ce51c142-8098-405a-9164-f554bd7a7007)

I tried all three options and got the same error, how can I fix that issue?
Thanks for the answers
Fakhrullo

**Comment by tersekmatija** [comment]
Hi @Fakhrillo ,

Can you please share how you trained your model? What repository and version was used?

**Comment by vanbergeijk** [comment]
Encountered the same issue with a pretrained model from https://datasetcolab.com/models#YOLOv6n

[YOLOv6nNORO.zip](https://github.com/luxonis/tools/files/14234893/YOLOv6nNORO.zip)
None of the YoloV6n versions could read and convert the .pt file, attached the file in zip archive.

Thank you for looking into this,
Jacob

**Comment by vanbergeijk** [comment]
Hello Jan, 

Thank you for looking into it, when I later chose the YoloV8 option to override the V6 (R2+R3) auto detect, the conversion tool did create a blob that ran OK on an OAK-D lite. Wondering whether there is something wrong with the header or format of the weights file? Or the weights file is actually a Yolo V8 rather than for a Yolo V6?

**Comment by HonzaCuhel** [comment]
Hi,

this is because the model was trained using the `ultralytics` library. Recently, they added YoloV6 support, including training, inference, export, etc. Therefore, even though the model has the structure of YoloV6 and is completely valid, it requires the `ultralytics` library to be loaded, which none of the YoloV6 convertors have installed. I have already locally updated the automatic version detector to select the Yolo version correctly. As soon as we deploy the change, we'll let you know. Until then, please use the Yolov8 conversion option. I apologize for the inconvenience. 

Best,
Jan
